// PreToolUse guard for Unity projects.
// - Blocks hand-written .meta files (Unity generates them).
// - Blocks edits to Unity-generated folders and files at the project root.
// - Asks for confirmation before any git push.
// Exit 2 blocks the call with stderr as the reason; JSON on stdout returns a permission decision.

const fs = require("fs");
const path = require("path");

const GeneratedFolders = ["Library", "Temp", "Logs", "obj"];
const FileTools = ["Write", "Edit", "MultiEdit", "NotebookEdit"];
const ShellTools = ["Bash", "PowerShell"];

function readInput() {
  try {
    return JSON.parse(fs.readFileSync(0, "utf8"));
  } catch {
    return null;
  }
}

function block(reason) {
  process.stderr.write(reason);
  process.exit(2);
}

function ask(reason) {
  process.stdout.write(JSON.stringify({
    hookSpecificOutput: {
      hookEventName: "PreToolUse",
      permissionDecision: "ask",
      permissionDecisionReason: reason,
    },
  }));
  process.exit(0);
}

function isUnityProject(root) {
  return fs.existsSync(path.join(root, "ProjectSettings", "ProjectVersion.txt"));
}

function checkFile(filePath, projectRoot) {
  if (!filePath) return;
  const normalized = filePath.replace(/\\/g, "/");

  if (normalized.toLowerCase().endsWith(".meta")) {
    block("Unity .meta files are generated by Unity, never written by hand. Leave asset creation to the user in the editor and list the steps instead.");
  }

  if (!projectRoot || !isUnityProject(projectRoot)) return;

  const relative = path.relative(projectRoot, path.resolve(projectRoot, filePath)).replace(/\\/g, "/");
  if (relative.startsWith("..")) return;

  const firstSegment = relative.split("/")[0];
  if (GeneratedFolders.includes(firstSegment)) {
    block(`${firstSegment}/ is generated by Unity and must not be edited.`);
  }
  if (!relative.includes("/") && /\.(csproj|sln|slnx)$/i.test(relative)) {
    block(`${relative} is generated by Unity. Copy it into the scratchpad for compile checks instead of editing it.`);
  }
}

function checkCommand(command) {
  // Matches `git push` and `git -C <dir> push` / `git --flag push`, not "push" inside a message.
  if (command && /\bgit(?:\s+-C\s+\S+|\s+-c\s+\S+|\s+--?[\w-]+(?:=\S+)?)*\s+push\b/.test(command)) {
    ask("git push needs explicit confirmation.");
  }
}

const input = readInput();
if (!input) process.exit(0);

const toolName = input.tool_name || "";
const toolInput = input.tool_input || {};
const projectRoot = process.env.CLAUDE_PROJECT_DIR || input.cwd;

if (FileTools.includes(toolName)) {
  checkFile(toolInput.file_path || toolInput.notebook_path, projectRoot);
} else if (ShellTools.includes(toolName)) {
  checkCommand(toolInput.command);
}

process.exit(0);
